version: "3.7"
services:
  app:
    image: veyvik87/lcdh:1.07
    restart: always
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./server.xml:/usr/local/tomcat/conf/server.xml
#services:
#  your-app:
#    image: your-app-image:latest
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./data:/path/to/your/database
#    depends_on:
#      - database
#
#  database:
#    image: h2database/h2:latest
#    environment:
#      - H2_DATABASE_NAME=lcdh
#      - H2_DATABASE_USERNAME=your_username
#      - H2_DATABASE_PASSWORD=your_password
#    volumes:
#      - ./data:/h2-data






#  grafana:
#    build: './scripts/config/grafana'
#    ports:
#      - 3000:3000
#    volumes:
#      - ./scripts/grafana:/var/lib/grafana
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin111
#      - GF_SECURITY_ADMIN_PASSWORD=admin111
#    networks:
#      monitoring:
#        aliases:
#          - grafana
#  prometheus:
#    image: prom/prometheus
#    ports:
#      - 9090:9090
#    volumes:
#      - ./scripts/config/prometheus.yml:/etc/prometheus/prometheus.yml
#      - ./scripts/prometheus:/prometheus
#    networks:
#      monitoring:
#        aliases:
#          - prometheus
#networks:
#  monitoring:



#version: "3.7"
#
#services:
#  nginx:
#    container_name: nginx
#    image: nginx:1.13
#    restart: always
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d
#      - web-root:/var/www/html
#      - certbot-etc:/etc/letsencrypt
#      - certbot-var:/var/lib/letsencrypt
#      - dhparam:/etc/ssl/certs
#    networks:
#      - app-network
#
#  certbot:
#    image: certbot/certbot
#    depends_on:
#      - nginx
#    container_name: certbot
#    volumes:
#      - certbot-etc:/etc/letsencrypt
#      - certbot-var:/var/lib/letsencrypt
#      - web-root:/var/www/html
#    command: certonly --webroot --webroot-path=/var/www/html --email lcdh@cigarsplace.ru --agree-tos --no-eff-email -d cigarsplace.ru -d www.cigarsplace.ru
#
#  app:
#    container_name: simple-spring-boot-app
#    image: veyvik87/lcdh:1.05
#    restart: always
#    expose:
#      - "80"
#    depends_on:
#      - nginx
#    networks:
#      - app-network
#
#volumes:
#  certbot-etc:
#  certbot-var:
#  web-root:
#  dhparam:
#    driver: local
#    driver_opts:
#      type: none
#      device: /root/dhparam/
#      o: bind
#
#networks:
#  app-network:
#    driver: bridge


