server:
  servlet:
    session:
      timeout: 180m
#  port: 80
  port: 443
  ssl:
    enabled: true
    key-store: /etc/letsencrypt/live/cigarsplace.ru/cert.p12
    key-store-password: cigarsplace123
    keyStoreType: PKCS12
spring:
  datasource:
#    url: jdbc:h2:file:./lcdh-data/lcdh;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=TRUE;DB_CLOSE_DELAY=-1;
#    url: jdbc:h2:mem:lcdh
    url: jdbc:mysql://tajipusup.beget.app:3306/default-db
    username: default-db
    password: Qqazaq1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  thymeleaf:
    cache: false
  mvc:
   format:
    date-time: dd-MM-yyyy HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
