server:
  servlet:
    session:
      timeout: 180m
  port: 80
#server:
#  port: 443
#  ssl:
#    enabled: true
#    key-store: /etc/letsencrypt/live/datetimeresult.ru/cert.p12
#    key-store-password: 83988398veyvik87
#    keyStoreType: PKCS12
spring:
  datasource:
#    url: jdbc:h2:file:./lcdh-data/lcdh;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=TRUE;DB_CLOSE_DELAY=-1;
    url: jdbc:h2:mem:lcdh
    username: admin
    password: nimda321
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: validate
    show-sql: false
  h2:
    console:
      enabled: true
      path: /ru/admin/h2-console
      settings:
        web-allow-others: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  thymeleaf:
    cache: false
  mvc:
   format:
    date-time: dd-MM-yyyy HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
